[appendix]

[#Event Trace Operations]
== Event Trace Operations (non-normative)

* Event Trace is a mode of the Trace Encoder which is set up with *trTeControl.trTeInstMode=4*. Then, *trTeControl.trTeEnable* is used to enable trace or disable and flush it, with *trTeControl.trTeEmpty* used to indicate when the flush has completed.
* *trTeEvtControl.trTeEvtTracing* is both a control and status bit. Reading it indicates Event Trace is tracing or not. Writing to it enables native software to start or stop Event Trace dynamically such as turning it off at the beginning of a function and turning it back on at the end, or visa versa.
* Event Trace can be started by native software writing to the Event Trace control registers. This can also be done with a JTAG command writing to the same registers.
* Event Trace can be first enabled via (for example) a hardware trigger set up to match on a program instruction address then, when the program-to-be-traced starts executing and the trigger match occurs, it in turn sets *trTeEvtControl.trTeEvtTracing*, and event trace starts.
* Once running, a hardware trigger previously set up to disable trace can, at the occurrence of a trigger match, turn Event Trace off which clears *trTeEvtControl.trTeEvtTracing*. Similar actions are common with Instruction Trace.
* An instrumented program can also clear or set *trTeEvtControl.trTeEvtTracing* to disable or enable Event Trace.
* Event Trace can be disabled by writing *trTeEvtControl.trTeEnable* = 0. This does a flush to the trace system.
* Trace can be set up to stop tracing on buffer full: *trRamControl.trRamStopOnWrap* = 1. When this occurs, Event Trace continues running, however no more trace messages are written to the trace buffer.
* A self-hosted trace analysis program such as Linux _perf_ could control the starting and stopping of Event Trace.
* Trace hardware supports on-the-fly switching between Event Trace and Instruction Trace. Memory-mapped (MMIO) hardware control registers allow a user program to change modes of trace so a trace recording can have both instruction trace messages intermixed with event trace messages. This feature allows the tracing of a portion of one program/process full execution while also tracing kernel-level events such as going in and out of kernel mode and running other processes. 
// More details are in section "Operational Description & Message Rules".
